language: ruby

before_script:
  - wget https://github.com/errata-ai/vale/releases/download/v1.2.6/vale_1.2.6_Linux_64-bit.tar.gz -O /tmp/vale.tar.gz
  - mkdir /tmp/vale
  - tar -xvzf /tmp/vale.tar.gz -C /tmp/vale
  - export PATH=$PATH:/tmp/vale

script: bundle exec danger
